"""
Research Gatekeeper
Main coordinator for the research system with quality control
"""

from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime
import logging
import json

from .config_manager import ConfigManager, get_config_manager
from .anthropic_integration import AnthropicIntegration
from .academic_research_aggregator import AcademicResearchAggregator, AggregatedResearch
from ..sources.base_source import ResearchPaper
from ..subagents.citation_tracker import CitationTracker
from ..subagents.credibility_analyzer import CredibilityAnalyzer
from ..subagents.insight_synthesizer import InsightSynthesizer
from ..subagents.fact_checker import FactChecker
from ..validation.research_validator import ResearchValidator, ValidationResult

logger = logging.getLogger(__name__)


@dataclass
class ResearchReport:
    """Complete research report generated by the gatekeeper"""
    topic: str
    query: str
    papers: List[ResearchPaper]
    synthesis: str
    insights: List[str]
    knowledge_gaps: List[str]
    validation_result: ValidationResult
    citations: List[Dict[str, Any]]
    metadata: Dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'topic': self.topic,
            'query': self.query,
            'total_papers': len(self.papers),
            'synthesis': self.synthesis,
            'insights': self.insights,
            'knowledge_gaps': self.knowledge_gaps,
            'validation': self.validation_result.to_dict(),
            'citations_count': len(self.citations),
            'metadata': self.metadata,
            'generated_at': self.generated_at.isoformat()
        }

    def save_to_file(self, filepath: str) -> None:
        """Save report to JSON file"""
        with open(filepath, 'w') as f:
            json.dump(self.to_dict(), f, indent=2)
        logger.info(f"Research report saved to {filepath}")


class ResearchGatekeeper:
    """
    Research Gatekeeper - Main Coordinator

    Orchestrates all research activities with quality gates:
    1. Conducts multi-database research
    2. Validates source credibility
    3. Synthesizes findings
    4. Enforces quality standards
    5. Generates comprehensive reports
    """

    def __init__(self, config_file: Optional[str] = None):
        """
        Initialize Research Gatekeeper

        Args:
            config_file: Optional path to configuration file
        """
        # Load configuration
        self.config = get_config_manager(config_file)

        # Initialize Anthropic API
        if self.config.api_config.anthropic_api_key:
            self.anthropic_api = AnthropicIntegration(
                api_key=self.config.api_config.anthropic_api_key,
                default_model=self.config.subagent_config.insight_synthesis_model
            )
        else:
            logger.warning("Anthropic API key not configured - AI features will be limited")
            self.anthropic_api = None

        # Initialize components
        self.aggregator = AcademicResearchAggregator(self.config)
        self.citation_tracker = CitationTracker()
        self.credibility_analyzer = CredibilityAnalyzer(self.anthropic_api)

        if self.anthropic_api:
            self.insight_synthesizer = InsightSynthesizer(self.anthropic_api)
            self.fact_checker = FactChecker(self.anthropic_api)
        else:
            self.insight_synthesizer = None
            self.fact_checker = FactChecker(None)

        self.validator = ResearchValidator(
            self.config,
            self.credibility_analyzer,
            self.citation_tracker
        )

        # Tracking
        self.iteration_count = 0
        self.research_history: List[ResearchReport] = []

        logger.info("Research Gatekeeper initialized successfully")
        logger.info(f"Available sources: {len(self.aggregator.registry)} databases")

    def conduct_research(
        self,
        topic: str,
        query: Optional[str] = None,
        year_from: Optional[int] = None,
        year_to: Optional[int] = None,
        focus_areas: Optional[List[str]] = None,
        min_quality_threshold: Optional[float] = None,
        max_iterations: Optional[int] = None
    ) -> ResearchReport:
        """
        Conduct comprehensive research with quality gates

        Args:
            topic: Research topic
            query: Specific search query (defaults to topic)
            year_from: Start year filter
            year_to: End year filter
            focus_areas: Specific areas to focus on
            min_quality_threshold: Minimum quality score (overrides config)
            max_iterations: Maximum refinement iterations (overrides config)

        Returns:
            ResearchReport with validated findings
        """
        query = query or topic
        max_iterations = max_iterations or self.config.system_config.max_iterations

        if min_quality_threshold:
            self.config.research_config.min_quality_threshold = min_quality_threshold

        logger.info(f"="*80)
        logger.info(f"Starting research on topic: {topic}")
        logger.info(f"Query: {query}")
        logger.info(f"="*80)

        self.iteration_count = 0
        validation_passed = False
        research_result = None
        validation_result = None

        while self.iteration_count < max_iterations and not validation_passed:
            self.iteration_count += 1
            logger.info(f"\n--- Iteration {self.iteration_count}/{max_iterations} ---")

            # Step 1: Aggregate research from all sources
            logger.info("Step 1: Aggregating research from multiple databases...")
            research_result = self.aggregator.search_all_sources(
                query=query,
                year_from=year_from,
                year_to=year_to
            )

            logger.info(f"Found {len(research_result.papers)} papers from {len(research_result.sources_succeeded)} sources")

            if not research_result.papers:
                logger.warning("No papers found. Adjust query or search parameters.")
                break

            # Step 2: Track citations
            logger.info("Step 2: Tracking citations...")
            self.citation_tracker.add_papers_bulk(research_result.papers)

            # Step 3: Analyze credibility
            logger.info("Step 3: Analyzing source credibility...")
            credible_papers = self.credibility_analyzer.filter_by_credibility(
                research_result.papers,
                min_score=7.0
            )
            logger.info(f"Filtered to {len(credible_papers)} credible papers")

            # Step 4: Validate research quality
            logger.info("Step 4: Validating research quality...")
            validation_result = self.validator.validate_research(credible_papers, topic)

            logger.info(f"Validation result: {'PASSED' if validation_result.passed else 'FAILED'}")
            logger.info(f"Overall quality score: {validation_result.overall_score:.1f}/10")

            if validation_result.passed:
                validation_passed = True
                logger.info("✓ Research meets quality standards!")
            else:
                logger.warning(f"✗ Quality threshold not met (iteration {self.iteration_count})")
                logger.info("Issues identified:")
                for issue in validation_result.issues:
                    logger.info(f"  - {issue}")
                logger.info("Recommendations:")
                for rec in validation_result.recommendations:
                    logger.info(f"  - {rec}")

                if self.iteration_count < max_iterations:
                    logger.info("Refining search parameters...")
                    # Could implement query refinement here

        # Use the best result we have
        if not research_result or not validation_result:
            raise RuntimeError("Research failed to produce results")

        final_papers = credible_papers if credible_papers else research_result.papers

        # Step 5: Synthesize insights (if AI available)
        logger.info("Step 5: Synthesizing research insights...")
        synthesis = ""
        insights = []
        knowledge_gaps = []

        if self.insight_synthesizer:
            try:
                synthesis = self.insight_synthesizer.synthesize_research(
                    papers=final_papers[:30],  # Limit for context
                    topic=topic,
                    focus_areas=focus_areas
                )

                insights = self.insight_synthesizer.generate_insights(
                    research_data={'papers': [p.to_dict() for p in final_papers[:20]]},
                    research_question=query
                )

                knowledge_gaps = self.insight_synthesizer.identify_knowledge_gaps(
                    research_synthesis=synthesis,
                    topic=topic
                )

                logger.info(f"Generated {len(insights)} insights and identified {len(knowledge_gaps)} knowledge gaps")
            except Exception as e:
                logger.error(f"Error during synthesis: {e}")
                synthesis = "Synthesis unavailable (AI error)"
        else:
            synthesis = "Synthesis unavailable (Anthropic API not configured)"
            logger.warning("Skipping synthesis - Anthropic API not available")

        # Step 6: Generate report
        logger.info("Step 6: Generating research report...")
        report = ResearchReport(
            topic=topic,
            query=query,
            papers=final_papers,
            synthesis=synthesis,
            insights=insights,
            knowledge_gaps=knowledge_gaps,
            validation_result=validation_result,
            citations=[c.to_dict() for c in self.citation_tracker.get_all_citations()],
            metadata={
                'iterations': self.iteration_count,
                'sources_queried': research_result.sources_queried,
                'sources_succeeded': research_result.sources_succeeded,
                'search_time': research_result.search_time,
                'credibility_filtered': len(research_result.papers) - len(final_papers)
            }
        )

        # Save to history
        self.research_history.append(report)

        # Save to file
        output_dir = self.config.system_config.output_directory
        import os
        os.makedirs(output_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c for c in topic if c.isalnum() or c in (' ', '_')).rstrip()[:50]
        filename = f"{output_dir}/research_{safe_topic}_{timestamp}.json"
        report.save_to_file(filename)

        logger.info(f"\n{'='*80}")
        logger.info(f"Research Complete!")
        logger.info(f"{'='*80}")
        logger.info(f"Topic: {topic}")
        logger.info(f"Papers: {len(final_papers)}")
        logger.info(f"Quality Score: {validation_result.overall_score:.1f}/10")
        logger.info(f"Status: {'PASSED' if validation_result.passed else 'NEEDS_IMPROVEMENT'}")
        logger.info(f"Report saved: {filename}")
        logger.info(f"{'='*80}\n")

        return report

    def quick_search(self, query: str, max_papers: int = 20) -> List[ResearchPaper]:
        """
        Quick search without full quality validation

        Args:
            query: Search query
            max_papers: Maximum papers to return

        Returns:
            List of research papers
        """
        logger.info(f"Quick search: {query}")

        result = self.aggregator.search_all_sources(
            query=query,
            max_papers_per_source=max_papers // 3
        )

        papers = result.papers[:max_papers]
        logger.info(f"Quick search found {len(papers)} papers")

        return papers

    def fact_check_claim(self, claim: str, topic: str) -> Dict[str, Any]:
        """
        Fact-check a claim using research

        Args:
            claim: Claim to fact-check
            topic: Related topic for research

        Returns:
            Fact-check result
        """
        logger.info(f"Fact-checking claim: {claim[:100]}...")

        # Get evidence
        evidence_papers = self.quick_search(topic, max_papers=15)

        # Check the claim
        result = self.fact_checker.check_claim(claim, evidence_papers, context=topic)

        logger.info(f"Fact-check verdict: {result.verdict} (confidence: {result.confidence}/10)")

        return result.to_dict()

    def get_statistics(self) -> Dict[str, Any]:
        """
        Get system statistics

        Returns:
            Statistics dictionary
        """
        return {
            'total_research_reports': len(self.research_history),
            'citations_tracked': len(self.citation_tracker),
            'sources_available': len(self.aggregator.registry),
            'source_statistics': self.aggregator.get_source_statistics(),
            'credibility_stats': self.credibility_analyzer.get_statistics()
        }

    def reset(self) -> None:
        """Reset all tracked data"""
        self.citation_tracker = CitationTracker()
        self.credibility_analyzer = CredibilityAnalyzer(self.anthropic_api)
        self.research_history = []
        self.iteration_count = 0
        self.aggregator.reset_statistics()
        logger.info("Research Gatekeeper reset complete")

    def __repr__(self) -> str:
        """String representation"""
        return f"ResearchGatekeeper(sources={len(self.aggregator.registry)}, reports={len(self.research_history)})"
